eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/

server:
  port: 8761

spring:
  cloud:
    config:
      override.system-properties: false